export enum DataExecutionErrorCode {
	CONCURRENT_QUERY,
	DATA_EXECUTION_ERROR_CODE_UNSPECIFIED,
	DATA_NOT_FOUND,
	DUPLICATE_COLUMN_NAMES,
	ENGINE,
	INTERRUPTED,
	MISSING_COLUMN_ALIAS,
	OBJECT_IN_ERROR_STATE,
	OBJECT_NOT_FOUND,
	OBJECT_SPEC_INVALID,
	OTHER,
	PARAMETER_INVALID,
	PERMISSION_DENIED,
	TIMED_OUT,
	TOO_MANY_CELLS,
	TOO_MANY_CHARS_PER_CELL,
	TOO_MANY_ROWS,
	UNSUPPORTED_DATA_TYPE
}

export enum ErrorCode {
	ERROR_CODE_UNSPECIFIED,
	DOCUMENT_TOO_LARGE_TO_EDIT,
	DOCUMENT_TOO_LARGE_TO_LOAD
}

export interface ErrorDetails {
	errorCode: ErrorCode;
}

export enum ErrorType {
	DIVIDE_BY_ZERO,
	ERROR,
	ERROR_TYPE_UNSPECIFIED,
	LOADING,
	NAME,
	NULL_VALUE,
	NUM,
	N_A,
	REF,
	VALUE
}

export interface ErrorValue {
	message: string;
	type: ErrorType;
}
