export enum BulletAlignment {
	BULLET_ALIGNMENT_UNSPECIFIED,
	CENTER,
	END,
	START
}

export enum BulletGlyphPreset {
	BULLET_ARROW3D_CIRCLE_SQUARE,
	BULLET_ARROW_DIAMOND_DISC,
	BULLET_CHECKBOX,
	BULLET_DIAMONDX_ARROW3D_SQUARE,
	BULLET_DIAMONDX_HOLLOWDIAMON_SQUARE,
	BULLET_DIAMOND_CIRCLE_SQUARE,
	BULLET_DISC_CIRCLE_SQUARE,
	BULLET_GLYPH_PRESET_UNSPECIFIED,
	BULLET_LEFTTRIANGLE_DIAMOND_DISC,
	BULLET_STAR_CIRCLE_SQUARE,
	NUMBERED_DECIMAL_ALPHA_ROMAN,
	NUMBERED_DECIMAL_ALPHA_ROMAN_PARENS,
	NUMBERED_DECIMAL_NESTED,
	NUMBERED_UPPERALPHA_ALPHA_ROMAN,
	NUMBERED_UPPERROMAN_UPPERALPHA_DECIMAL,
	NUMBERED_ZERODECIMAL_ALPHA_ROMAN
}

export enum GlyphType {
	ALPHA,
	DECIMAL,
	GLYPH_TYPE_UNSPECIFIED,
	NONE,
	ROMAN,
	UPPER_ALPHA,
	UPPER_ROMAN,
	ZERO_DECIMAL
}

export enum HeaderFooterType {
	DEFAULT,
	HEADER_FOOTER_TYPE_UNSPECIFIED
}

export enum ImageReplaceMethod {
	CENTER_CROP,
	IMAGE_REPLACE_METHOD_UNSPECIFIED
}

export enum PositionedObjectLayout {
	BREAK_LEFT,
	BREAK_LEFT_RIGHT,
	BREAK_RIGHT,
	IN_FRONT_OF_TEXT,
	POSITIONED_OBJECT_LAYOUT_UNSPECIFIED,
	WRAP_TEXT
}

export enum PropertyState {
	NOT_RENDERED,
	RENDERED
}
